#!MC 1120
# Created by Tecplot 360 build 11.3.29.563
$!VarSet |MFBD| = ''
$!EXPORTSETUP EXPORTFORMAT = PNG
$!EXPORTSETUP EXPORTREGION = ALLFRAMES
$!EXPORTSETUP IMAGEWIDTH = 1500
$!EXPORTSETUP EXPORTFNAME = '__temp.png'
$!EXPORT 
  EXPORTREGION = ALLFRAMES
$!RemoveVar |MFBD|
